gripper_camera_node: "link_raised_gripper"
top_camera_node: "camera_depth_optical_frame"
gripper_left_fingertip_node: "link_gripper_fingertip_left"
gripper_right_fingertip_node: "link_gripper_fingertip_right"

config:
  # [move, pick]
  mode: "pick"
  # ["gripper_camera", "top_camera", "gripper_left", "gripper_right"]
  base_frame: "top_camera"
  # Frame transform
  transform: true
  # ["gripper_camera", "top_camera", "gripper_left", "gripper_right"]
  transformed_frame: "gripper_left"

robot:
  # Initial arm height
  init_lift: 0.7
  # Initial wrist pitch angle
  # (0 - straight picks, -1.57 - top down picks)
  init_pitch: 0
  # correction in final x y and z
  correction:
    # (0.1 - )
    x: 0.1
    y: -0.03
    z: 0.025
  
